# Generated by Django 4.0.5 on 2022-06-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
